laguage: java
jdk: oraclejdk8
install: mvn package -P sonatype -D skipTests
script: mvn --settings travis-mvn-settings.xml -P sonatype verify
deploy:
  provider: script
  script: mvn --settings travis-mvn-settings.xml -P sonatype clean deploy
  on: {branch: master}